#define _GNU_SOURCE

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <fcntl.h>
#include <ctype.h>

// #define DEBUG

void print_error(){
    fprintf(stderr, "An error has occurred\n");
}

char* trim_string(char *str){
    size_t len = strlen(str)-1;
    char *new_str = str;

    // Trim suffix
    while(str[len] == ' '){
        len--;
    }

    str[len+1] = '\0';

    // trim prefix
    while(*new_str == ' '){
        new_str++;
    }

    return new_str;
}

int count_character(const char *str, const char chr){
    if (str == NULL) {
        return 0;
    }

    int occurance = 0;
    size_t len = strlen(str);

    for (int i = 0; i < len; i++){
        if (str[i] == chr){
            occurance++;
        }
    }

    return occurance;
}

int handle_redirect(const char *filename){
    int fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

    int result = dup2(fd, 1);
    close(fd);

    return result;
}


void execv_command(char *path, char* command, char* args){
    char *token;
    int num_of_args;

    // Parse args into multiple arguments
    if (args == NULL) {
        num_of_args = 0;
    } else {
        num_of_args = count_character(args, ' ');
        num_of_args++;
    }
    
    num_of_args += 2;

    #ifdef DEBUG
        printf("DEBUG: execv, path:%s command:%s, args:%s\n", path, command, args);
    #endif


    char *argv[num_of_args];
    argv[0] = command;
    for (int i = 1; i < num_of_args-1; i++){
        token = strsep(&args, " ");

         argv[i] = token;

        #ifdef DEBUG
            printf("    DEBUG: execv, argv[%d]:%s\n", i, argv[i]);
        #endif
    }
    argv[num_of_args-1] = NULL;
    // execv()
    execv(path, argv);
    exit(0);
}

int execute_command(char* command, char *args, const char *redirect, char *search_path){
    char full_command[50];
    char copy_path[50];
    const char *path;
    strcpy(copy_path, search_path);
    bool found = false;
    int is_executable;

    pid_t child_pid;

    char* temp_path = copy_path;
    // Checking if the command exist in the search_path
    while((path = strsep(&temp_path, " "))) {
        snprintf(full_command, sizeof(full_command), "%s/%s", path, command);
        is_executable = access(full_command, X_OK);

        if (is_executable == 0) {
            found = true;
            break;
        }
    }

    if (!found) {
        print_error();
        return 1;
    }

    // If yes fork() and execv() to execute comand
    child_pid = fork();

    switch (child_pid) {
        // is child
        case 0:

            // handle redirect
            if (redirect != NULL) {
                if (*command == '\0') {
                    print_error();
                    exit(1);
                }
                handle_redirect(redirect);
            }

            execv_command(full_command, command, args);
            break;
        // is parent
        default:
            // waitpid(child_pid, wstatus, 0);   
            break;
    }

    return 0;
}

int handle_command(char *full_command, ssize_t len, char *search_path) {
    int err;

    // Change the newline in command string to null terminated
    // newline is generated by getline(3)
    full_command[len-1] = '\0';

    // 
    // Handle parsing here
    // 

    // extract multi command
    char *individual_command = NULL;
    char *first_argument;
    char *command;

    while (full_command != NULL) {
        command = strsep(&full_command, "&");

        command = trim_string(command);

        // handle redirect
        const char *redirect = strchr(command, '>');
        // Redirection found
        if (redirect != NULL) {
            // Separate the string
            individual_command = strsep(&command, ">");

            // Trim the redirection
            const char *redirect_token = trim_string(command);

            if (*redirect_token == '\0'){
                print_error();
                return 1;
            }

            // Check ' ' and '>', if exist throw error
            redirect = strchr(redirect_token, ' ');
            if (redirect != NULL){
                print_error();
                return 1;
            }
            redirect = strchr(redirect_token, '>');
            if (redirect != NULL){
                print_error();
                return 1;
            }
            
            // Convert redirect to remainder_token
            redirect = redirect_token;
        } else {
            individual_command = command;
        }

        // Exit function
        if (strncmp(individual_command, "exit", 4) == 0){
            if (strlen(individual_command) == 4){
                exit(0);
            } else {
                print_error();
            }
        } else if (strncmp(individual_command, "cd", 2) == 0){
            strsep(&individual_command, " ");
            if (individual_command == NULL) {
                print_error();
            } else if (count_character(individual_command, ' ') > 0) {
                print_error();
            } else {
                err = chdir(individual_command);
                if (err != 0){
                    exit(1);
                }
            }
        } else if (strncmp(individual_command, "path", 4) == 0) {
            strsep(&individual_command, " ");
            if (individual_command == NULL) {
                search_path[0] = '\0';
            } else {
                strcpy(search_path, individual_command);
            }
            
        } else {
            // Other command via path
            if (search_path[0] == '\0') {
                print_error();
                return 1;
            }
            first_argument = strsep(&individual_command, " ");

            execute_command(first_argument, individual_command, redirect, search_path);
        }
    }

    int status;
    while(wait(&status) > 0){}
}

void interactive_mode(){
    char *user_input = NULL;
    size_t len;
    ssize_t nread;

    char search_path[50] = "/bin";

    const char *current_directory = NULL;

    while(1) {
        current_directory = get_current_dir_name();
        // printf("wish> (%s) ", current_directory);
        printf("wish> ");
        fflush(stdout);
        
        nread = getline(&user_input, &len, stdin);

        if (nread == 0){
            exit(1);
        }

        if (nread == 1){
            continue;
        }

        handle_command(user_input, nread, search_path);
    }
}

void batch_mode(int argc, char *argv[]){
    FILE* file;
    char *line = NULL;
    ssize_t nread;
    size_t len;

    char search_path[50] = "/bin";

    if (argc > 2){
        print_error();
        exit(1);
    }

    for (int i = 1; i < argc; i++){
        // Open file one-by-one

        file = fopen(argv[i], "r");

        if (file == NULL){
            print_error();
            exit(1);
        }
        
        while((nread = getline(&line, &len, file))){

            if (nread == -1) {
                break;
            }
            handle_command(line, nread, search_path);
        }

        fclose(file);
    }
}

int main(int argc, char *argv[]){
    // Checking argc if == 1 enter interactive mode
    if (argc == 1) {
        interactive_mode();
    } else if (argc >= 2) {
        batch_mode(argc, argv);
    } else {
        return 1;
    }

    return 0;
}
