#define _GNU_SOURCE

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <fcntl.h>

// #define DEBUG

void print_error(){
    fprintf(stderr, "An error has occurred\n");
}

int count_character(char *str, const char chr){
    if (str == NULL) {
        return 0;
    }

    int occurance = 0;
    size_t len = strlen(str);

    for (int i = 0; i < len; i++){
        if (str[i] == chr){
            occurance++;
        }
    }

    return occurance;
}

int handle_redirect(char *filename){
    int fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

    int result = dup2(fd, 1);
    close(fd);

    return result;
}


void execv_command(char *path, char* command, char* args){
    char *token;
    int num_of_args;

    // Parse args into multiple arguments
    if (args == NULL) {
        num_of_args = 0;
    } else {
        num_of_args = count_character(args, ' ');
        num_of_args++;
    }
    
    num_of_args += 2;

    #ifdef DEBUG
        printf("DEBUG: execv, path:%s command:%s, args:%s\n", path, command, args);
    #endif


    char *argv[num_of_args];
    argv[0] = command;
    for (int i = 1; i < num_of_args-1; i++){
        token = strsep(&args, " ");

         argv[i] = token;

        #ifdef DEBUG
            printf("    DEBUG: execv, argv[%d]:%s\n", i, argv[i]);
        #endif
    }
    argv[num_of_args-1] = NULL;
    // execv()
    execv(path, argv);
    exit(0);
}

int execute_command(char* command, char *args, char *redirect, char *search_path){
    char full_command[50];
    char *path = NULL;
    bool found = false;
    int is_executable;

    pid_t child_pid;
    int *wstatus;

    #ifdef DEBUG
    printf("DEBUG: search path: %s\n", search_path);
    #endif

    // Checking if the command exist in the search_path
    while((path = strsep(&search_path, " "))) {
        snprintf(full_command, sizeof(full_command), "%s/%s", path, command);
        is_executable = access(full_command, X_OK);

        #ifdef DEBUG
        printf("DEBUG: Full command: %s\n", full_command);
        #endif

        if (is_executable == 0) {
            found = true;
            break;
        }
    }

    if (!found) {
        print_error();
        return 1;
    }

    // If yes fork() and execv() to execute comand
    child_pid = fork();

    switch (child_pid) {
        // is child
        case 0:

            // handle redirect
            if (redirect != NULL) {
                handle_redirect(redirect);
            }

            execv_command(full_command, command, args);
            break;
        // is parent
        default:
            // waitpid(child_pid, wstatus, 0);   
            break;
    }
}

int execute_commands(char* first_command, char *remainder_token, char *search_path) {
    char *args = NULL;

    char *tmp_command;
    char *tmp_args;
    char *redirect = NULL;

    // check redirection
    if (remainder_token != NULL) {
        redirect = strchr(remainder_token, '>');
    }

    if (redirect != NULL) {
        if (remainder_token != redirect) {
            args = strsep(&remainder_token, " > ");
        }
        
        remainder_token++;
        if (strchr(remainder_token, '>') != NULL) {
                print_error();
                return 1;
        }   

        // trim the string
        while (*remainder_token == ' '){
            remainder_token++;
        }

        // No string after redirect token
        if (*remainder_token == '\0') {
            print_error();
            return 1;
        }

        // multiple word checking
        if (strchr(remainder_token, ' ') != NULL) {
            print_error();
            return 1;
        }

        redirect = remainder_token;
    } else {
        args = remainder_token;
    }

    // parse multiple commands
    int num_of_commands = count_character(args, '&') + 1;

    tmp_args = strsep(&args, "&");

    // execute first command
    execute_command(first_command, tmp_args, redirect, search_path);

    for (int i = 1; i < num_of_commands; i++) {
        tmp_command = strsep(&args, " ");
        tmp_args = strsep(&args, "&");

        execute_command(tmp_command, tmp_args, redirect, search_path);
    }

    int status;
    while(wait(&status) > 0){}
}

void handle_command(char *command, ssize_t len, char *search_path) {
    char *first_arg;
    int err;

    // Change the newline in command string to null terminated
    // newline is generated by getline(3)
    command[len-1] = '\0';

    first_arg = strsep(&command, " ");

    #ifdef DEBUG
    printf("DEBUG: first: %s Remaining: %s\n", first_arg, command);
    #endif

    // Exit function
    if (strcmp(first_arg, "exit") == 0){
        if (command == NULL){
            exit(0);
        } else {
            print_error();
        }
    } else if (strcmp(first_arg, "cd") == 0){
        if (command == NULL) {
            print_error();
        } else if (count_character(command, ' ') > 0) {
            print_error();
        } else {
            err = chdir(command);
            if (err != 0){
                exit(1);
            }
        }
    } else if (strcmp(first_arg, "path") == 0) {
        if (command == NULL) {
            search_path[0] = '\0';
        } else {
            strcpy(search_path, command);
        }
        
        #ifdef DEBUG
        printf("DEBUG: change search_path to: %s\n", search_path);
        #endif

    } else {
        // Other command via path
        if (search_path[0] == '\0') {
            print_error();
            return;
        }
        execute_commands(first_arg, command, search_path);
    }
}

void interactive_mode(){
    char *user_input = NULL;
    size_t len;
    ssize_t nread;

    char search_path[50] = "/bin";

    char *current_directory = NULL;

    while(1) {
        current_directory = get_current_dir_name();
        // printf("wish> (%s) ", current_directory);
        printf("wish> ");
        fflush(stdout);
        
        nread = getline(&user_input, &len, stdin);

        if (nread == 0){
            exit(1);
        }

        if (nread == 1){
            continue;
        }

        handle_command(user_input, nread, search_path);
    }
}

void batch_mode(int argc, char *argv[]){
    FILE* file;
    char *line = NULL;
    ssize_t nread;
    size_t len;

    char search_path[50] = "/bin";

    for (int i = 1; i < argc; i++){
        // Open file one-by-one

        file = fopen(argv[i], "r");
        
        while((nread = getline(&line, &len, file))){

            if (nread == -1) {
                break;
            }
            handle_command(line, nread, search_path);
        }

        fclose(file);
    }
}

int main(int argc, char *argv[]){
    // Checking argc if == 1 enter interactive mode
    if (argc == 1) {
        interactive_mode();
    } else if (argc >= 2) {
        batch_mode(argc, argv);
    } else {
        return 1;
    }

    return 0;
}
